name: ghostwave_bt
description: "GhostWaveBT - Bluetooth Car Controller with 8-Direction Movement"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.9
  permission_handler: ^12.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/GhostWaveBT.png
  
  # Remove unused material icons for smaller APK
  generate: false

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/GhostWaveBT.png"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/images/GhostWaveBT.png"